# Generated by Django 5.1.4 on 2024-12-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_post_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
    ]
